name: C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: write
      actions: write
      
    strategy:
      matrix:
        include:
          - name: 64-bit
            arch-double: arm64-v8a

          - name: 32-bit
            arch-double: armeabi-v7a
    
    runs-on:
      ubuntu-latest
      # - nscloud-ubuntu-24.04-amd64-8x8-with-cache
      # - nscloud-git-mirror-5gb
      # - nscloud-cache-size-20gb
      # - nscloud-cache-tag-FOGLTLOGLES
    
    steps:
    # - uses: namespacelabs/nscloud-setup@v0
    
    # - uses: namespacelabs/nscloud-checkout-action@v5
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 21

    - name: Install CCache
      uses: Chocobo1/setup-ccache-action@v1
      with:
        override_cache_key: ccache-FOGLTLOGLES-${{ matrix.arch-double }}-cache

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    # - name: Setup Android SDK
    #  uses: android-actions/setup-android@v3
    #  with:
    #    packages: 'ndk;28.0.13004108'

    - name: Build
      run: |
        chmod +x build.sh
        bash build.sh ${{ matrix.arch-double }}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: FOGLTOGLES - ${{ matrix.name }}
        path: | 
          build/*.so

  trigger:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger Renderer Plugin workflow
        run: |
          repo_owner="ThatMG393-2" 
          repo_name="FOGLTLOGLES-RendererPlugin"  
          event_type="update-fogle-submod"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"

      - name: Trigger MojoLauncher_FOGLTLOGLES workflow
        run: |
          repo_owner="ThatMG393-2" 
          repo_name="MojoLauncher_FOGLTLOGLES"  
          event_type="update-fogle-binary"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"

