name: C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: 64-bit
            arch-double: arm64-v8a

          - name: 32-bit
            arch-double: armeabi-v7a
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1

    - name: Install CCache
      uses: Chocobo1/setup-ccache-action@v1
      with:
        ccache_options: |
          compression=false

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Build
      run: |
        ./utils/git-sync-deps
        mkdir b && cd b
        cmake -G Ninja .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.arch-double }} \
          -DANDROID_PLATFORM=android-26 \
          -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: FOGLTOGLES - ${{ matrix.name }}
        path: | 
          b/*.so
