name: C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - name: 64-bit
            arch-double: arm64-v8a

          - name: 32-bit
            arch-double: armeabi-v7a
    
    runs-on:
      ubuntu-latest
      # - nscloud-ubuntu-24.04-amd64-8x8-with-cache
      # - nscloud-git-mirror-5gb
      # - nscloud-cache-size-20gb
      # - nscloud-cache-tag-FOGLTLOGLES
    
    steps:
    # - uses: namespacelabs/nscloud-setup@v0
    
    # - uses: namespacelabs/nscloud-checkout-action@v5
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 21

    - name: Install CCache
      uses: Chocobo1/setup-ccache-action@v1
      with:
        ccache_options: |
          compression=false

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    # - name: Setup Android SDK
    #  uses: android-actions/setup-android@v3
    #  with:
    #    packages: 'ndk;28.0.13004108'

    - name: Build
      run: |
        chmod +x build.sh
        bash build.sh ${{ matrix.arch-double }}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: FOGLTOGLES - ${{ matrix.name }}
        path: | 
          build/*.so
