name: C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
          - name: 64-bit
            arch-double: arm64-v8a

          - name: 32-bit
            arch-double: armeabi-v7a
    
    runs-on: namespace-profile-anglebuild
    steps:
    - uses: namespacelabs/nscloud-setup@v0
    
    - uses: namespacelabs/nscloud-checkout-action@v5
      with:
        submodules: true
        fetch-depth: 1

    - name: Install CCache
      uses: Chocobo1/setup-ccache-action@v1
      with:
        ccache_options: |
          compression=false

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install ANDK
      uses: nttld/setup-ndk@v1
      with:
        link-to-sdk: true
        ndk-version: r28

    - name: Build
      run: |
        chmod +x build.sh
        bash build.sh ${{ matrix.arch-double }}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: FOGLTOGLES - ${{ matrix.name }}
        path: | 
          build/*.so
